/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Figuras;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaEsfera extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaEsfera
     */
    public VentanaEsfera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRadio = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblVolumen = new javax.swing.JLabel();
        lblSuperficie = new javax.swing.JLabel();
        imgEsfera = new javax.swing.JLabel();

        setTitle("Esfera");

        lblRadio.setText("Radio(cms)");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblVolumen.setText("Volumen (cm3): ");

        lblSuperficie.setText("Superficie (cm2): ");

        imgEsfera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/esfera.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSuperficie)
                    .addComponent(lblVolumen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(55, 55, 55)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRadio)
                        .addGap(18, 18, 18)
                        .addComponent(txtRadio)))
                .addGap(18, 18, 18)
                .addComponent(imgEsfera, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRadio)
                            .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalcular)
                            .addComponent(btnLimpiar))
                        .addGap(35, 35, 35)
                        .addComponent(lblVolumen)
                        .addGap(18, 18, 18)
                        .addComponent(lblSuperficie)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(imgEsfera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try{
            double radio = Double.parseDouble(txtRadio.getText());
            
            Esfera AuxEsf = new Esfera(radio);
            
            lblVolumen.setText("Volumen (cm3): " + String.format("%.2f", AuxEsf.volumen) );
            lblSuperficie.setText("Superficie (cm2): " + String.format("%.2f", AuxEsf.superficie) );
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Caracteres no validos");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtRadio.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel imgEsfera;
    private javax.swing.JLabel lblRadio;
    private javax.swing.JLabel lblSuperficie;
    private javax.swing.JLabel lblVolumen;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
